version: '3'
services:
  postgres:
    container_name: postgres
    image: parrotstream/postgres:10.5
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    privileged: true
  hadoop-hive:
    container_name: hadoop-hive
    image: hadoop-hive:0.1
    external_links:
    - zookeeper
    depends_on:
    - postgres
    environment:
      PGPASSWORD: postgres
    ports:
    - 9870:9870
    - 9864:9864
    - 9820:9820
    - 8042:8042
    - 8088:8088
    - 8188:8188
    - 19888:19888
    - 10000:10000
    - 10001:10001
    - 10002:10002
    - 10003:10003
    - 9083:9083
    - 50111:50111
    - 9999:9999
networks:
  default:
    external:
      name: parrot_default
