version: "3"
services:
  hadoop:
    container_name: hadoop
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/hadoop:3.0.3
    external_links:
    - zookeeper
    ports:
    - 9870:9870
    - 9864:9864
    - 9820:9820
    - 8042:8042
    - 8088:8088
    - 8188:8188
    - 19888:19888
networks:
  default:
    external:
      name: parrot_default